create MASTER KEY ENCRYPTION BY PASSWORD = 'WLY|SNb2C*F"N2oAIisc?6B)ouc6PN?v]H<%PD-X.7X-t%HG~//b$hFgrv@GbKn1g2A0=|MCI)D>Hcyw!';

CREATE CERTIFICATE MyCert 
WITH SUBJECT = 'Password Encryption';

CREATE SYMMETRIC KEY MySymmetricKey
WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE MyCert;